AllCops:
  NewCops: enable
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideRangeLiteral:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Metrics/MethodLength:
  Max: 29
Metrics/AbcSize:
  Max: 43
